# This file is based on the original work from Grafana Labs © 2023.
# Modifications were made by Cloud Rhino Pty Ltd @ 2024.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Modifications:
# - added install az cli to the original grafana docker image to test Azure Managed Identity authentication locally
# - added resource limits to allow for more container resources 

version: '3.8'

services:
  grafana:
    container_name: infinity-plus-datasource
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000/tcp
    volumes:
      - ./provisioning/dashboards-actual/:/dashboards/
      - ./provisioning:/etc/grafana/provisioning
      - ./dist:/var/lib/grafana/plugins/infinity-plus-datasource
      # Attach Azure CLI credentials from the host for local development
      - ~/.azure:/usr/share/grafana/.azure
    environment:
      - TERM=linux
      - GF_DEFAULT_APP_MODE=development # Set to development mode for local testing
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_SECURITY_ADMIN_USER=infinity
      - GF_SECURITY_ADMIN_PASSWORD=infinity
      - GF_SECURITY_ANGULAR_SUPPORT_ENABLED=false
      - GF_SECURITY_CSRF_ALWAYS_CHECK=true
      - GF_ENTERPRISE_LICENSE_TEXT=$GF_ENTERPRISE_LICENSE_TEXT
    user: root  # Run container as root to ensure write permissions
    command: >
      sh -c "chown -R grafana:grafana /usr/share/grafana/.azure && /run.sh"  # Fix permissions before running the Grafana entrypoint
    deploy:
      resources:
        limits:
          memory: 1024M
          cpus: "1.0"
        reservations:
          memory: 256M
          cpus: "0.25"
