# This file is based on the original work from Grafana Labs © 2023.
# Modifications were made by Cloud Rhino Pty Ltd @ 2024.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Modifications:
# - Added support for local Azure CLI credentials to test Azure Managed Identity authentication.
# - Set Grafana to development mode for easier testing and plugin development.
# - Enabled anonymous access and set admin credentials for ease of use in a development environment.
# - Added debugging tools such as Loki and Tempo for advanced logging and tracing.

version: '3.7'
x-logging: &default-logging
  driver: loki
  options:
    loki-url: 'http://localhost:3100/api/prom/push'

services:
  microsocks:
    container_name: microsocks
    image: vimagick/microsocks
    ports:
      - 1080:1080

  loki:
    image: grafana/loki:main
    command: -config.file=/etc/loki/loki-config.yaml
    volumes:
      - ./docker/blocks/loki/config.yaml:/etc/loki/loki-config.yaml
    ports:
      - "3100:3100"

  tempo:
    image: grafana/tempo:latest
    depends_on:
      - loki
    command:
      - --config.file=/etc/tempo.yaml
    volumes:
      - ./docker/blocks/tempo/config.yaml:/etc/tempo.yaml
    ports:
      - "14268:14268"   # jaeger ingest
      - "3200:3200"     # tempo
      - "4317:4317"     # otlp grpc
      - "4318:4318"     # otlp http

  grafana:
    container_name: infinity-plus-datasource
    logging: *default-logging
    image: grafana/grafana-enterprise:${GF_VERSION:-main}
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - microsocks
      - loki
      - tempo
    ports:
      - '3000:3000'
    volumes:
      - ./provisioning/dashboards-actual/:/dashboards/
      - ./provisioning:/etc/grafana/provisioning
      - ./dist/:/var/lib/grafana/plugins/infinity-plus-datasource
      # Attach Azure CLI credentials from the host for local development
      - ~/.azure:/root/.azure 
    environment:
      - TERM=linux
      - GF_DEFAULT_APP_MODE=development
      - GF_LOG_LEVEL=debug
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_SECURITY_ADMIN_USER=infinity
      - GF_SECURITY_ADMIN_PASSWORD=infinity
      - GF_SECURITY_ANGULAR_SUPPORT_ENABLED=false
      - GF_SECURITY_CSRF_ALWAYS_CHECK=true
      - GF_ENTERPRISE_LICENSE_TEXT=$GF_ENTERPRISE_LICENSE_TEXT
      - GF_FEATURE_TOGGLES_ENABLE=publicDashboards topnav dataConnectionsConsole newPanelChromeUI emptyDashboardPage correlations nestedFolders advancedDataSourcePicker secureSocksDSProxyEnabled
      - GF_PLUGIN_YESOREYERAM_INFINITY_DATASOURCE_TRACING=true
      - GF_TRACING_OPENTELEMETRY_OTLP_ADDRESS=tempo:4317
      - GF_TRACING_OPENTELEMETRY_OTLP_PROPAGATION=w3c,jaeger
      - GF_INSTANCE_OTLP_ADDRESS=tempo:4317
      - GF_INSTANCE_OTLP_PROPAGATION=w3c,jaeger
      - GF_SECURE_SOCKS_DATASOURCE_PROXY_ENABLED=true
      - GF_SECURE_SOCKS_DATASOURCE_PROXY_PROXY_ADDRESS=microsocks:1080
      - GF_SECURE_SOCKS_DATASOURCE_PROXY_ALLOW_INSECURE=true
