version: '3.7'

services:
  grafana:
    container_name: infinity-plus-datasource
    platform: linux/amd64
    image: grafana/grafana-enterprise:${GF_VERSION:-main}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./provisioning/dashboards-actual/:/dashboards/
      - ./provisioning:/etc/grafana/provisioning
      - ./dist:/var/lib/grafana/plugins/infinity-plus-datasource
      - ~/.azure:/root/.azure # Modification: Attach Azure CLI credentials from the host for local development
    environment:
      - TERM=linux
      - GF_DEFAULT_APP_MODE=development # Modification: Set to development mode to indicate local testing
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_SECURITY_ADMIN_USER=infinity
      - GF_SECURITY_ADMIN_PASSWORD=infinity
      - GF_SECURITY_ANGULAR_SUPPORT_ENABLED=false
      - GF_SECURITY_CSRF_ALWAYS_CHECK=true
      - GF_ENTERPRISE_LICENSE_TEXT=$GF_ENTERPRISE_LICENSE_TEXT
