blank_issues_enabled: false
contact_links:
  - name: General Questions?
    url: https://github.com/cloudrhinoltd/infinity-plus-datasource/discussions/new?category=q-a
    about: Use our Q&A Section in our docs to get answers for your questions.
  - name: Specific API?
    url: https://github.com/cloudrhinoltd/infinity-plus-datasource/discussions/new?category=specific-apis
    about: Questions about specific APIs. You may find answers here: https://github.com/cloudrhinoltd/infinity-plus-datasource/discussions/categories/specific-apis
  - name: Feature Request?
    url: https://github.com/cloudrhinoltd/infinity-plus-datasource/discussions/new?category=ideas
    about: Have an interesting idea to improve InfinityPlus? Or see any missing killer features?
  - name: Showcase
    url: https://github.com/cloudrhinoltd/infinity-plus-datasource/discussions/new?category=show-and-tell
    about: Have an inspiring use-case? Use our show & tell section to share with the community.
  - name: Docs
    url: https://grafana.com/docs/plugins/yesoreyeram-infinity-datasource
    about: Documentation for the original Grafana Infinity Datasource, applicable to InfinityPlus.
  - name: Bug in UQL?
    url: https://github.com/yesoreyeram/uql
    about: If you find any bugs in UQL queries, please report them here.
  - name: Bug in GROQ?
    url: https://github.com/sanity-io/groq-js/issues
    about: If you find any bugs in GROQ queries, please report them here.
